services:

  database_instance:
    image: mysql:latest
    container_name: javadao_db
    volumes:
      - db_volume_name:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306

volumes:
  db_volume_name:
    external: false
